uint16 KEY_W = 1
uint16 KEY_S = 2
uint16 KEY_A = 4
uint16 KEY_D = 8
uint16 KEY_LSHIFT = 16
uint16 KEY_LCTRL = 32
uint16 KEY_Q = 64
uint16 KEY_E = 128
uint16 KEY_R = 256
uint16 KEY_F = 512
uint16 KEY_G = 1024
uint16 KEY_Z = 2048
uint16 KEY_X = 4096
uint16 KEY_C = 8192
uint16 KEY_V = 16384
uint16 KEY_B = 32768

std_msgs/Header header
int16 mouse_x
int16 mouse_y
int16 mouse_z
int8 left_button_down
int8 right_button_down
uint16 keyboard_value
uint16 reserved